### PR TITLE
Ideal emission comparison graph (and reformatting)

### PR DESCRIPTION
**Pull request by RW21**
image

Give me design suggetions please. Thanks.

### CODE REVIEW

**Comment by IvanImp** [comment]
1. Try it with a lower px line for the graph.
2. don't bold the emission in grams.
3. if you gonna go grams with K, why not go kilograms as label?
4. backdrop doesn't need the green
5. "Weekly" can be smaller

**Comment by pu-pu** [comment]
To add on to what Ivan suggested.
- Decrease the size of the y-axis (Kilogram Number; 0, 2k, 4k) label to match with the x-axis label.

**Comment by RW21** [comment]
@IvanImp @pu-pu 
How is it now?
image

**Comment by pu-pu** [comment]
Can you add a bit more space between Weekly and the graph?

**Comment by IvanImp** [comment]
Looking a lot better, I have nothing to add on for now, need to see a bigger picture to have more ideas.

**Comment by RW21** [comment]
image

**Comment by pu-pu** [comment]
Yup.. Looks good.

**Pull request merged**
