### PR TITLE
Initial implementation of community and firestore

### PR DESCRIPTION
**Pull request by RW21**
**Important**: Package name is changed. Please check if it builds properly on your machine.

### CODE REVIEW

**Review by IvanImp — CHANGES_REQUESTED** [review]
You didnt push your cloud_firestore and firebase_auth to the branch, I can't run on my machine without those files

**Comment by RW21** [comment]
@IvanImp Did you `pub get`? Those files don't exist.

**Comment by IvanImp** [comment]
My bad, I did pub get, but didnt restart my code

**Review by xhhh-mendes — APPROVED** [review]
Sry I don't have my laptop with me today & tomorrow. I'll test it later then.

Thanks for your work!

**Comment by IvanImp** [comment]
image

**Comment by RW21** [comment]
@IvanImp See the new `README.md`. I have also mentioned this on messenger.

**Comment by IvanImp** [comment]
image

**Comment by RW21** [comment]
@IvanImp  You should've gotten an invitation email.

**Comment by IvanImp** [comment]
The login isn't supposed to be working right? Its gonna be on a future branch?

**Comment by RW21** [comment]
@IvanImp Login is working but the screen currently doesn't change.

**Pull request merged**
